[package]
name = "automeme"
version = "0.1.0"
authors = ["wasabipesto <automeme@wasabipesto.com>"]
description = "a meme generator stapled to a web server"
repository = "https://github.com/wasabipesto/automeme"
license-file = "LICENSE"
edition = "2021"

[dependencies]
